# Generated by Django 4.2.4 on 2023-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register')], max_length=10),
        ),
    ]
