# Generated by Django 4.2.4 on 2023-08-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_emailrecord_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrecord',
            name='user',
        ),
    ]
