# Generated by Django 4.2.4 on 2023-08-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_survey_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswerdetail',
            old_name='useranswer_id',
            new_name='useranswer',
        ),
    ]
