# Generated by Django 4.2.4 on 2023-08-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_category_survey_remove_tag_survey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
