# Generated by Django 4.2.4 on 2023-08-21 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0005_alter_survey_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
