# Generated by Django 4.2.4 on 2023-08-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_remove_survey_tags_tag_survey_tag_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='survey',
        ),
        migrations.AddField(
            model_name='survey',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='surveys.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='surveys',
            field=models.ManyToManyField(related_name='surveys', to='surveys.survey'),
        ),
    ]
