# Generated by Django 4.2.4 on 2023-08-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_remove_tag_surveys_alter_survey_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
