# Generated by Django 4.2.4 on 2023-08-22 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_remove_answer_body_remove_answer_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys.answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_text',
            field=models.TextField(),
        ),
    ]
