# Generated by Django 4.2.4 on 2023-08-22 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_useranswer_answer_point_alter_useranswer_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_point',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
    ]
