# Generated by Django 4.2.4 on 2023-08-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_alter_useranswer_answer_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.answer'),
        ),
    ]
