# Generated by Django 4.2.4 on 2023-08-23 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_alter_useranswer_answer_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.category'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='surveys', to='surveys.tag'),
        ),
    ]
