# Generated by Django 4.2.4 on 2023-08-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_alter_survey_category_alter_survey_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='AnswerOption',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='writer',
        ),
    ]
