# Generated by Django 4.2.4 on 2023-08-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_remove_useranswer_answer_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerdetail',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
