# Generated by Django 4.2.4 on 2023-08-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sleeping',
            field=models.BooleanField(default=True),
        ),
    ]
