# Generated by Django 4.2.4 on 2023-08-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
