# Generated by Django 4.2.4 on 2023-08-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_email_opt_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_opt_in',
        ),
        migrations.AddField(
            model_name='user',
            name='email_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
