# Generated by Django 4.2.4 on 2023-08-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_sleeping'),
        ('user', '0006_remove_profile_email_opt_in_user_email_opt_in'),
    ]

    operations = [
    ]
